const LITCANON_NOVELS = [
  { id: "ulysses", title: "Ulysses", author: "James Joyce" },
  { id: "the-great-gatsby", title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
  { id: "a-portrait-of-the-artist-as-a-young-man", title: "A Portrait of the Artist as a Young Man", author: "James Joyce" },
  { id: "lolita", title: "Lolita", author: "Vladimir Nabokov" },
  { id: "brave-new-world", title: "Brave New World", author: "Aldous Huxley" },
  { id: "the-sound-and-the-fury", title: "The Sound and the Fury", author: "William Faulkner" },
  { id: "catch-22", title: "Catch-22", author: "Joseph Heller" },
  { id: "darkness-at-noon", title: "Darkness at Noon", author: "Arthur Koestler" },
  { id: "sons-and-lovers", title: "Sons and Lovers", author: "D.H. Lawrence" },
  { id: "the-grapes-of-wrath", title: "The Grapes of Wrath", author: "John Steinbeck" },
  { id: "under-the-volcano", title: "Under the Volcano", author: "Malcolm Lowry" },
  { id: "the-way-of-all-flesh", title: "The Way of All Flesh", author: "Samuel Butler" },
  { id: "1984", title: "1984", author: "George Orwell" },
  { id: "i-claudius", title: "I, Claudius", author: "Robert Graves" },
  { id: "to-the-lighthouse", title: "To the Lighthouse", author: "Virginia Woolf" },
  { id: "an-american-tragedy", title: "An American Tragedy", author: "Theodore Dreiser" },
  { id: "the-heart-is-a-lonely-hunter", title: "The Heart Is a Lonely Hunter", author: "Carson McCullers" },
  { id: "slaughterhouse-five", title: "Slaughterhouse-Five", author: "Kurt Vonnegut" },
  { id: "invisible-man", title: "Invisible Man", author: "Ralph Ellison" },
  { id: "native-son", title: "Native Son", author: "Richard Wright" },
  { id: "henderson-the-rain-king", title: "Henderson the Rain King", author: "Saul Bellow" },
  { id: "appointment-in-samarra", title: "Appointment in Samarra", author: "John O'Hara" },
  { id: "usa", title: "U.S.A.", author: "John Dos Passos" },
  { id: "winesburg-ohio", title: "Winesburg, Ohio", author: "Sherwood Anderson" },
  { id: "a-passage-to-india", title: "A Passage to India", author: "E.M. Forster" },
  { id: "the-wings-of-the-dove", title: "The Wings of the Dove", author: "Henry James" },
  { id: "the-ambassadors", title: "The Ambassadors", author: "Henry James" },
  { id: "tender-is-the-night", title: "Tender Is the Night", author: "F. Scott Fitzgerald" },
  { id: "the-studs-lonigan-trilogy", title: "The Studs Lonigan Trilogy", author: "James T. Farrell" },
  { id: "the-good-soldier", title: "The Good Soldier", author: "Ford Madox Ford" },
  { id: "animal-farm", title: "Animal Farm", author: "George Orwell" },
  { id: "the-golden-bowl", title: "The Golden Bowl", author: "Henry James" },
  { id: "sister-carrie", title: "Sister Carrie", author: "Theodore Dreiser" },
  { id: "a-handful-of-dust", title: "A Handful of Dust", author: "Evelyn Waugh" },
  { id: "as-i-lay-dying", title: "As I Lay Dying", author: "William Faulkner" },
  { id: "all-the-kings-men", title: "All the King's Men", author: "Robert Penn Warren" },
  { id: "the-bridge-of-san-luis-rey", title: "The Bridge of San Luis Rey", author: "Thornton Wilder" },
  { id: "howards-end", title: "Howards End", author: "E.M. Forster" },
  { id: "go-tell-it-on-the-mountain", title: "Go Tell It on the Mountain", author: "James Baldwin" },
  { id: "the-heart-of-the-matter", title: "The Heart of the Matter", author: "Graham Greene" },
  { id: "lord-of-the-flies", title: "Lord of the Flies", author: "William Golding" },
  { id: "deliverance", title: "Deliverance", author: "James Dickey" },
  { id: "a-dance-to-the-music-of-time", title: "A Dance to the Music of Time", author: "Anthony Powell" },
  { id: "point-counter-point", title: "Point Counter Point", author: "Aldous Huxley" },
  { id: "the-sun-also-rises", title: "The Sun Also Rises", author: "Ernest Hemingway" },
  { id: "the-secret-agent", title: "The Secret Agent", author: "Joseph Conrad" },
  { id: "nostromo", title: "Nostromo", author: "Joseph Conrad" },
  { id: "the-rainbow", title: "The Rainbow", author: "D.H. Lawrence" },
  { id: "women-in-love", title: "Women in Love", author: "D.H. Lawrence" },
  { id: "tropic-of-cancer", title: "Tropic of Cancer", author: "Henry Miller" },
  { id: "the-naked-and-the-dead", title: "The Naked and the Dead", author: "Norman Mailer" },
  { id: "portnoys-complaint", title: "Portnoy's Complaint", author: "Philip Roth" },
  { id: "pale-fire", title: "Pale Fire", author: "Vladimir Nabokov" },
  { id: "light-in-august", title: "Light in August", author: "William Faulkner" },
  { id: "on-the-road", title: "On the Road", author: "Jack Kerouac" },
  { id: "the-maltese-falcon", title: "The Maltese Falcon", author: "Dashiell Hammett" },
  { id: "parades-end", title: "Parade's End", author: "Ford Madox Ford" },
  { id: "the-age-of-innocence", title: "The Age of Innocence", author: "Edith Wharton" },
  { id: "zuleika-dobson", title: "Zuleika Dobson", author: "Max Beerbohm" },
  { id: "the-moviegoer", title: "The Moviegoer", author: "Walker Percy" },
  { id: "death-comes-for-the-archbishop", title: "Death Comes for the Archbishop", author: "Willa Cather" },
  { id: "from-here-to-eternity", title: "From Here to Eternity", author: "James Jones" },
  { id: "the-wapshot-chronicles", title: "The Wapshot Chronicles", author: "John Cheever" },
  { id: "the-catcher-in-the-rye", title: "The Catcher in the Rye", author: "J.D. Salinger" },
  { id: "a-clockwork-orange", title: "A Clockwork Orange", author: "Anthony Burgess" },
  { id: "of-human-bondage", title: "Of Human Bondage", author: "W. Somerset Maugham" },
  { id: "heart-of-darkness", title: "Heart of Darkness", author: "Joseph Conrad" },
  { id: "main-street", title: "Main Street", author: "Sinclair Lewis" },
  { id: "the-house-of-mirth", title: "The House of Mirth", author: "Edith Wharton" },
  { id: "the-alexandria-quartet", title: "The Alexandria Quartet", author: "Lawrence Durrell" },
  { id: "a-high-wind-in-jamaica", title: "A High Wind in Jamaica", author: "Richard Hughes" },
  { id: "a-house-for-mr-biswas", title: "A House for Mr Biswas", author: "V.S. Naipaul" },
  { id: "the-day-of-the-locust", title: "The Day of the Locust", author: "Nathanael West" },
  { id: "a-farewell-to-arms", title: "A Farewell to Arms", author: "Ernest Hemingway" },
  { id: "scoop", title: "Scoop", author: "Evelyn Waugh" },
  { id: "the-prime-of-miss-jean-brodie", title: "The Prime of Miss Jean Brodie", author: "Muriel Spark" },
  { id: "finnegans-wake", title: "Finnegans Wake", author: "James Joyce" },
  { id: "kim", title: "Kim", author: "Rudyard Kipling" },
  { id: "a-room-with-a-view", title: "A Room with a View", author: "E.M. Forster" },
  { id: "brideshead-revisited", title: "Brideshead Revisited", author: "Evelyn Waugh" },
  { id: "the-adventures-of-augie-march", title: "The Adventures of Augie March", author: "Saul Bellow" },
  { id: "angle-of-repose", title: "Angle of Repose", author: "Wallace Stegner" },
  { id: "a-bend-in-the-river", title: "A Bend in the River", author: "V.S. Naipaul" },
  { id: "the-death-of-the-heart", title: "The Death of the Heart", author: "Elizabeth Bowen" },
  { id: "lord-jim", title: "Lord Jim", author: "Joseph Conrad" },
  { id: "ragtime", title: "Ragtime", author: "E.L. Doctorow" },
  { id: "the-old-wives-tale", title: "The Old Wives' Tale", author: "Arnold Bennett" },
  { id: "the-call-of-the-wild", title: "The Call of the Wild", author: "Jack London" },
  { id: "loving", title: "Loving", author: "Henry Green" },
  { id: "midnights-children", title: "Midnight's Children", author: "Salman Rushdie" },
  { id: "tobacco-road", title: "Tobacco Road", author: "Erskine Caldwell" },
  { id: "ironweed", title: "Ironweed", author: "William Kennedy" },
  { id: "the-magus", title: "The Magus", author: "John Fowles" },
  { id: "wide-sargasso-sea", title: "Wide Sargasso Sea", author: "Jean Rhys" },
  { id: "under-the-net", title: "Under the Net", author: "Iris Murdoch" },
  { id: "sophies-choice", title: "Sophie's Choice", author: "William Styron" },
  { id: "the-sheltering-sky", title: "The Sheltering Sky", author: "Paul Bowles" },
  { id: "the-postman-always-rings-twice", title: "The Postman Always Rings Twice", author: "James M. Cain" },
  { id: "the-ginger-man", title: "The Ginger Man", author: "J.P. Donleavy" },
  { id: "the-magnificent-ambersons", title: "The Magnificent Ambersons", author: "Booth Tarkington" },
  { id: "american-pastoral", title: "American Pastoral", author: "Philip Roth" },
  { id: "are-you-there-god-its-me-margaret", title: "Are You There God? It's Me, Margaret", author: "Judy Blume" },
  { id: "the-assistant", title: "The Assistant", author: "Bernard Malamud" },
  { id: "at-swim-two-birds", title: "At Swim-Two-Birds", author: "Flann O'Brien" },
  { id: "atonement", title: "Atonement", author: "Ian McEwan" },
  { id: "beloved", title: "Beloved", author: "Toni Morrison" },
  { id: "the-berlin-stories", title: "The Berlin Stories", author: "Christopher Isherwood" },
  { id: "the-big-sleep", title: "The Big Sleep", author: "Raymond Chandler" },
  { id: "the-blind-assassin", title: "The Blind Assassin", author: "Margaret Atwood" },
  { id: "blood-meridian", title: "Blood Meridian", author: "Cormac McCarthy" },
  { id: "call-it-sleep", title: "Call It Sleep", author: "Henry Roth" },
  { id: "the-confessions-of-nat-turner", title: "The Confessions of Nat Turner", author: "William Styron" },
  { id: "the-corrections", title: "The Corrections", author: "Jonathan Franzen" },
  { id: "the-crying-of-lot-49", title: "The Crying of Lot 49", author: "Thomas Pynchon" },
  { id: "a-death-in-the-family", title: "A Death in the Family", author: "James Agee" },
  { id: "dog-soldiers", title: "Dog Soldiers", author: "Robert Stone" },
  { id: "falconer", title: "Falconer", author: "John Cheever" },
  { id: "the-french-lieutenants-woman", title: "The French Lieutenant's Woman", author: "John Fowles" },
  { id: "the-golden-notebook", title: "The Golden Notebook", author: "Doris Lessing" },
  { id: "gone-with-the-wind", title: "Gone with the Wind", author: "Margaret Mitchell" },
  { id: "gravitys-rainbow", title: "Gravity's Rainbow", author: "Thomas Pynchon" },
  { id: "herzog", title: "Herzog", author: "Saul Bellow" },
  { id: "housekeeping", title: "Housekeeping", author: "Marilynne Robinson" },
  { id: "infinite-jest", title: "Infinite Jest", author: "David Foster Wallace" },
  { id: "the-lion-the-witch-and-the-wardrobe", title: "The Lion, the Witch and the Wardrobe", author: "C.S. Lewis" },
  { id: "the-lord-of-the-rings", title: "The Lord of the Rings", author: "J.R.R. Tolkien" },
  { id: "lucky-jim", title: "Lucky Jim", author: "Kingsley Amis" },
  { id: "the-man-who-loved-children", title: "The Man Who Loved Children", author: "Christina Stead" },
  { id: "money", title: "Money", author: "Martin Amis" },
  { id: "mrs-dalloway", title: "Mrs. Dalloway", author: "Virginia Woolf" },
  { id: "naked-lunch", title: "Naked Lunch", author: "William S. Burroughs" },
  { id: "neuromancer", title: "Neuromancer", author: "William Gibson" },
  { id: "never-let-me-go", title: "Never Let Me Go", author: "Kazuo Ishiguro" },
  { id: "one-flew-over-the-cuckoos-nest", title: "One Flew Over the Cuckoo's Nest", author: "Ken Kesey" },
  { id: "the-painted-bird", title: "The Painted Bird", author: "Jerzy Kosinski" },
  { id: "play-it-as-it-lays", title: "Play It as It Lays", author: "Joan Didion" },
  { id: "possession", title: "Possession", author: "A.S. Byatt" },
  { id: "the-power-and-the-glory", title: "The Power and the Glory", author: "Graham Greene" },
  { id: "rabbit-run", title: "Rabbit, Run", author: "John Updike" },
  { id: "red-harvest", title: "Red Harvest", author: "Dashiell Hammett" },
  { id: "the-recognitions", title: "The Recognitions", author: "William Gaddis" },
  { id: "revolutionary-road", title: "Revolutionary Road", author: "Richard Yates" },
  { id: "snow-crash", title: "Snow Crash", author: "Neal Stephenson" },
  { id: "the-sot-weed-factor", title: "The Sot-Weed Factor", author: "John Barth" },
  { id: "the-sportswriter", title: "The Sportswriter", author: "Richard Ford" },
  { id: "the-spy-who-came-in-from-the-cold", title: "The Spy Who Came In from the Cold", author: "John le Carre" },
  { id: "their-eyes-were-watching-god", title: "Their Eyes Were Watching God", author: "Zora Neale Hurston" },
  { id: "things-fall-apart", title: "Things Fall Apart", author: "Chinua Achebe" },
  { id: "to-kill-a-mockingbird", title: "To Kill a Mockingbird", author: "Harper Lee" },
  { id: "ubik", title: "Ubik", author: "Philip K. Dick" },
  { id: "watchmen", title: "Watchmen", author: "Alan Moore and Dave Gibbons" },
  { id: "white-noise", title: "White Noise", author: "Don DeLillo" },
  { id: "white-teeth", title: "White Teeth", author: "Zadie Smith" },
  { id: "uncle-toms-cabin", title: "Uncle Tom's Cabin", author: "Harriet Beecher Stowe" },
  { id: "the-jungle", title: "The Jungle", author: "Upton Sinclair" },
  { id: "the-handmaids-tale", title: "The Handmaid's Tale", author: "Margaret Atwood" },
  { id: "alls-well-that-ends-well", title: "All's Well That Ends Well", author: "William Shakespeare" },
  { id: "as-you-like-it", title: "As You Like It", author: "William Shakespeare" },
  { id: "comedy-of-errors", title: "Comedy of Errors", author: "William Shakespeare" },
  { id: "loves-labours-lost", title: "Love's Labour's Lost", author: "William Shakespeare" },
  { id: "measure-for-measure", title: "Measure for Measure", author: "William Shakespeare" },
  { id: "merchant-of-venice", title: "Merchant of Venice", author: "William Shakespeare" },
  { id: "merry-wives-of-windsor", title: "Merry Wives of Windsor", author: "William Shakespeare" },
  { id: "midsummer-nights-dream", title: "Midsummer Night's Dream", author: "William Shakespeare" },
  { id: "much-ado-about-nothing", title: "Much Ado about Nothing", author: "William Shakespeare" },
  { id: "taming-of-the-shrew", title: "Taming of the Shrew", author: "William Shakespeare" },
  { id: "tempest", title: "Tempest", author: "William Shakespeare" },
  { id: "twelfth-night", title: "Twelfth Night", author: "William Shakespeare" },
  { id: "two-gentlemen-of-verona", title: "Two Gentlemen of Verona", author: "William Shakespeare" },
  { id: "winters-tale", title: "Winter's Tale", author: "William Shakespeare" },
  { id: "henry-iv-parts-i-and-ii", title: "Henry IV, Parts I & II", author: "William Shakespeare" },
  { id: "henry-v", title: "Henry V", author: "William Shakespeare" },
  { id: "henry-vi-parts-i-iii", title: "Henry VI, Part I-III", author: "William Shakespeare" },
  { id: "henry-viii", title: "Henry VIII", author: "William Shakespeare" },
  { id: "king-john", title: "King John", author: "William Shakespeare" },
  { id: "pericles", title: "Pericles", author: "William Shakespeare" },
  { id: "richard-ii", title: "Richard II", author: "William Shakespeare" },
  { id: "richard-iii", title: "Richard III", author: "William Shakespeare" },
  { id: "antony-and-cleopatra", title: "Antony and Cleopatra", author: "William Shakespeare" },
  { id: "coriolanus", title: "Coriolanus", author: "William Shakespeare" },
  { id: "cymbeline", title: "Cymbeline", author: "William Shakespeare" },
  { id: "hamlet", title: "Hamlet", author: "William Shakespeare" },
  { id: "julius-caesar", title: "Julius Caesar", author: "William Shakespeare" },
  { id: "king-lear", title: "King Lear", author: "William Shakespeare" },
  { id: "macbeth", title: "Macbeth", author: "William Shakespeare" },
  { id: "othello", title: "Othello", author: "William Shakespeare" },
  { id: "romeo-and-juliet", title: "Romeo and Juliet", author: "William Shakespeare" },
  { id: "timon-of-athens", title: "Timon of Athens", author: "William Shakespeare" },
  { id: "titus-andronicus", title: "Titus Andronicus", author: "William Shakespeare" },
  { id: "troilus-and-cressida", title: "Troilus and Cressida", author: "William Shakespeare" }
];
