const poemDatabase = [
  {
    id: "sonnet18-opening",
    title: "Sonnet 18",
    author: "William Shakespeare",
    difficulty: "easy",
    lines: [
      "Shall I compare thee to a summer’s day?",
      "Thou art more lovely and more temperate:",
      "Rough winds do shake the darling buds of May,",
      "And summer’s lease hath all too short a date;",
      "Sometime too hot the eye of heaven shines,",
      "And often is his gold complexion dimm'd;",
      "And every fair from fair sometime declines,",
      "By chance or nature’s changing course untrimm'd;",
      "But thy eternal summer shall not fade,",
      "Nor lose possession of that fair thou ow’st;",
      "Nor shall death brag thou wander’st in his shade,",
      "When in eternal lines to time thou grow’st:",
      "\u00A0\u00A0\u00A0So long as men can breathe or eyes can see,",
      "\u00A0\u00A0\u00A0So long lives this, and this gives life to thee."
    ],
    stanzas: ["1-4", "5-8", "9-12", "13-14"],
    dialog: [
  "Shakespeare addressed this and many other sonnets to a man. I wonder what his wife thought about that.",
  "Shakespeare published 154 sonnets in 1609. When you're done with this one, we'll start on the rest.",
  "Personally, I find the final couplet a bit cheeky."
]
  },
  {
    id: "virgins-opening",
    title: "To the Virgins, to Make Much of Time",
    author: "Robert Herrick",
    difficulty: "easy",
    lines: [
      "Gather ye rosebuds while ye may,",
      "   Old Time is still a-flying;",
      "And this same flower that smiles today",
      "   Tomorrow will be dying.",
      "",
      "The glorious lamp of heaven, the sun,",
      "   The higher he’s a-getting,",
      "The sooner will his race be run,",
      "   And nearer he’s to setting.",
      "",
      "That age is best which is the first,",
      "   When youth and blood are warmer;",
      "But being spent, the worse, and worst",
      "   Times still succeed the former.",
      "",
      "Then be not coy, but use your time,",
      "   And while ye may, go marry;",
      "For having lost but once your prime,",
      "   You may forever tarry."
    ],
    stanzas: ["1-4", "6-9", "11-14", "16-19"],
    dialog: [
      "Come out, Virginia, don't let me wait\nYou Catholic girls start much too late\nBut sooner or later it comes down to fate\nI might as well will be the one\nOnly the good die young",
      "Herrick joined the 'Sons of Ben,' a Ben Jonson fan club, and wrote five poems addressed to Jonson. Nerd.",
      "Herrick remained a bachelor all his life, leaving no evidence that he ever collected any rosebuds."
    ],
  },
    {
    id: "daffodils-opening",
    title: "I Wandered Lonely as a Cloud",
    author: "William Wordsworth",
    difficulty: "easy",
    lines: [
      "I wandered lonely as a cloud",
      "That floats on high o'er vales and hills,",
      "When all at once I saw a crowd,",
      "A host, of golden daffodils;",
      "Beside the lake, beneath the trees,",
      "Fluttering and dancing in the breeze.",
      "[...]",
      "For oft, when on my couch I lie",
      "In vacant or in pensive mood,",
      "They flash upon that inward eye",
      "Which is the bliss of solitude;",
      "And then my heart with pleasure fills,",
      "And dances with the daffodils."
    ],
    stanzas: ["1-6", "8-13"],
    dialog: [
      "Lord Byron and Samuel Taylor Coleridge both offered harsh criticism of Wordsworth's poetry.",
      "Romanticism is more about being receptive to strong emotions than the modern lovey-dovey meanince of romance. But I still like it when someone buys me flowers.",
      "Wordsworth was born in the small Cumbrian town of Cockermouth. Population roughly 2,500.",
    ],
  },

  {
    id: "she-walks-in-beauty",
    title: "She Walks in Beauty",
    author: "George Gordon, Lord Byron",
    difficulty: "easy",
    lines: [
      "She walks in beauty, like the night",
      "Of cloudless climes and starry skies;",
      "And all that’s best of dark and bright",
      "Meet in her aspect and her eyes;",
      "Thus mellowed to that tender light",
      "Which heaven to gaudy day denies.",
      "[...]",
      "And on that cheek, and o’er that brow,",
      "So soft, so calm, yet eloquent,",
      "The smiles that win, the tints that glow,",
      "But tell of days in goodness spent,",
      "A mind at peace with all below,",
      "A heart whose love is innocent!"
    ],
    stanzas: ["1-6", "8-13"],
    dialog: [
      "Though Byron was born in 1788, this poem actually dates back to before the destruction of the Second Temple in 70AD.",
      "Byron fought against the Ottoman Empire in the Greek War of Independence. He died at age 36 and is considered a hero in Greece.",
      "Byron's daughter Ada Lovelace is considered the mother of computer programming and the first tech nepobaby."
    ],
  },

  {
    id: "o-captain-my-captain",
    title: "O Captain! My Captain!",
    author: "Walt Whitman",
    difficulty: "easy",
    lines: [
      "O Captain! my Captain! our fearful trip is done,",
      "The ship has weather’d every rack, the prize we sought is won,",
      "The port is near, the bells I hear, the people all exulting,",
      "While follow eyes the steady keel, the vessel grim and daring;",
      "But O heart! heart! heart!",
      "O the bleeding drops of red,",
      "Where on the deck my Captain lies,",
      "Fallen cold and dead.",
      "",
      "O Captain! my Captain! rise up and hear the bells;",
      "Rise up—for you the flag is flung—for you the bugle trills,",
      "For you bouquets and ribbon’d wreaths—for you the shores a-crowding,",
      "For you they call, the swaying mass, their eager faces turning;",
      "Here Captain! dear father!",
      "This arm beneath your head!",
      "It is some dream that on the deck,",
      "You’ve fallen cold and dead.",
    ],
    stanzas: ["1-8", "10-17"],
    dialog: [
      "Yawp!",
      "So far, my research has not indicated that Abraham Lincoln was ever the captain of a ship.",
      "During the Civil War, Whitman worked as a volunteer nurse. Unfortunately, there are no surviving photos of him in his candy striper outfit."
    ],
  },

  {
    id: "road-not-taken",
    title: "The Road Not Taken",
    author: "Robert Frost",
    difficulty: "easy",
    lines: [
      "Two roads diverged in a yellow wood,",
      "And sorry I could not travel both",
      "And be one traveler, long I stood",
      "And looked down one as far as I could",
      "To where it bent in the undergrowth;",
      "",
      "Then took the other, as just as fair,",
      "And having perhaps the better claim,",
      "Because it was grassy and wanted wear;",
      "Though as for that the passing there",
      "Had worn them really about the same,",
      "[...]",
      "I shall be telling this with a sigh",
      "Somewhere ages and ages hence:",
      "Two roads diverged in a wood, and I—",
      "I took the one less traveled by,",
      "And that has made all the difference."
    ],
    stanzas: ["1-5", "7-11", "13-17"],
    dialog: [
      "Most people don't realize that the final stanza is a joke.",
      "This poem was based on a walk with Frost's friend, Edward Thomas. Its message inspired Thomas to enlist in WWI, where he was killed two years later.",
      "The title has been used in hundreds of book and chapter titles, and almost none of those folks have understood what the poem is actually saying."
    ],
  },

      {
    id: "portuguese",
    title: "Sonnets from the Portuguese 43",
    author: "Elizabeth Barrett Browning",
    difficulty: "elite",
    lines: [
      "How do I love thee? Let me count the ways.",
      "I love thee to the depth and breadth and height",
      "My soul can reach, when feeling out of sight",
      "For the ends of being and ideal grace.",
      "I love thee to the level of every day’s",
      "Most quiet need, by sun and candle-light.",
      "I love thee freely, as men strive for right;",
      "I love thee purely, as they turn from praise.",
      "I love thee with the passion put to use",
      "In my old griefs, and with my childhood’s faith.",
      "I love thee with a love I seemed to lose",
      "With my lost saints. I love thee with the breath,",
      "Smiles, tears, of all my life; and, if God choose,",
      "I shall but love thee better after death."
    ],
    stanzas: ["1-4", "5-8", "9-14"],
    dialog: [
  "Elizabeth's husband encouraged her to publish, saying they were the best sonnets since Shakespeare. This may have been around the time their son, Robert ('Pen'), was conceieved.",
  "The collection was originally written in English, but titled to make it seem like they were translations.",
  "Browning wrote that she wanted the souls of poets soaked with the blood of Christ. I'm probably leaving out some context.",
],
  },
];
